.\" kkeditcli
.TH "kkeditcli" "1" "0.0.0" "K.D.Hedger" "User Commands"
.SH "NAME"
kkeditcli \- manual page for kkeditcli 0.0.0
.SH "SYNOPSIS"
.B kkeditcli
.SH "DESCRIPTION"
A CLI programme.


.SH "EXAMPLES"
.LP 
	does somithing
.IP 
kkeditcli
.LP 

.SH "REPORTING BUGS"
Report bugs to kdhedger@yahoo.co.uk
